[settings]
idiomatic_version_file_enable_tools = ["node", "python", "rust"]
experimental = true

[tools]
node = "lts"
python = "3.14"
rust = "stable"
go = "1.27"
lua = "5.5"
pnpm = "latest"
kubie = "latest"
uv = "latest"
flux2 = "latest"
helm = "latest"
bun = "latest"
flyctl = "latest"
talosctl = "latest"
gh = "latest"
claude = "latest"
openbao = { version = "latest", exe = "bao" }
fnox = "latest"
age = "latest"
nub = { version = "latest", allow_builds = ["@nubjs/nub"] }
aube = "latest"
pulumi = "latest"
"pipx:semble" = "latest"
k9s = "latest"
azure-cli = { version = "latest", uvx_args = "--prerelease=allow" }
"github:vietz-dev/azie" = "0.0.1-pre.5028eeb"
"github:brocode/fblog" = "latest"

[env]
_.file = ".env"

[shell_alias]
# kubectl
k = "kubectl"
kg = "kubectl get"
kd = "kubectl describe"
kl = "kubectl logs"
kaf = "kubectl apply -f"
kx = "kubectl exec -it"

# git
g = "git"
gs = "git status -sb"
ga = "git add"
gc = "git commit"
gco = "git checkout"
gd = "git diff"
gp = "git push"
gl = "git pull"
glg = "git log --oneline --graph --decorate -20"
